# for travis-ci
# see also. https://travis-ci.org
language: php
sudo: required
php:
  #- 5.3.3
  #- 5.3
  #- 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1

matrix:
  fast_finish: true

env:
    global:
        - DBNAME=myapp_test HTTP_URL=http://localhost:8000 HTTPS_URL=https://localhost:8000
    matrix:
        - DB=mysql USER=root DBPASS=' ' DBUSER=root 
        - DB=pgsql USER=postgres DBPASS=password DBUSER=postgres 

before_script:
  - composer self-update || true
  - if [[ $TRAVIS_PHP_VERSION == '5.3.3' ]]; then composer install --dev --no-interaction --prefer-source ; fi
  - if [[ $TRAVIS_PHP_VERSION != '5.3.3' ]]; then composer install --dev --no-interaction ; fi
  - sh -c "if [ '$DB' = 'mysql' ]; then sh ./eccube_install.sh mysql; fi"
  - sh -c "if [ '$DB' = 'pgsql' ]; then sh ./eccube_install.sh pgsql; fi"
  - cp tests/require.php.jenkins tests/require.php
  - cat ./data/config/config.php
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - php -S localhost:8085 --docroot html &>/dev/null&
  - php vendor/bin/codecept build

script:
    #- mkdir -p reports/coverage
    #- phpunit -c phpunit.xml.dist
  - php vendor/bin/codecept run

after_script:
    #- php vendor/bin/coveralls -v

# Cache folder, you can delete cache from Travis CI web interface
cache:
    directories:
        - vendor
        - $HOME/.composer/cache vendor/
