# for travis-ci
# see also. https://travis-ci.org
language: php
sudo: required
php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - 7.2

matrix:
  fast_finish: true

env:
    global:
        - DBNAME=myapp_test HTTP_URL=http://localhost:8085/ HTTPS_URL=https://localhost:8085/
    matrix:
        - DB=mysql USER=root DBPASS=' ' DBUSER=root 
        - DB=pgsql USER=postgres DBPASS=password DBUSER=postgres 

before_script:
    ## see https://github.com/symfony/symfony/blob/e0bdc0c35e9afdb3bee8af172f90e9648c4012fc/.travis.yml#L92-L97
  - phpenv config-rm xdebug.ini || true
  - echo "opcache.enable_cli=1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - echo "apc.enable_cli=1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - composer self-update || true
  - composer install --dev --no-interaction -o --apcu-autoloader
  - sh -c "if [ '$DB' = 'mysql' ]; then sh ./eccube_install.sh mysql; fi"
  - sh -c "if [ '$DB' = 'pgsql' ]; then sh ./eccube_install.sh appveyor; fi"
  - cat ./data/config/config.php
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - php -S localhost:8085 -t html/ &
  - php data/vendor/bin/codecept build

script:
  - mkdir -p reports/coverage
  - php data/vendor/bin/phpunit -c phpunit.xml.dist
  - php data/vendor/bin/codecept run --env travis --steps

after_script:
  - php data/vendor/bin/coveralls -v
  - tail -n 100 ./data/logs/error.log

# Cache folder, you can delete cache from Travis CI web interface
cache:
    directories:
        - data/vendor
        - $HOME/.composer/cache vendor/
